//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void getHeading(void); \
	void setshoot(); \
	void PrintData(); \
	void setup(); \
	void loop(); \
	void compare(); \

